// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: vision_v2_wifi

#ifndef _VISION_V2_WIFI_UI_H
#define _VISION_V2_WIFI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Logo1;
extern lv_obj_t * ui_Model_Name;
extern lv_obj_t * ui_vision_image_1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_seeed_logo_png);    // assets/seeed_logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
